name = "Gemoded Ist Geil V2"
author = "Laputa Werkstatt"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "650c70ce9d7fb203ba165d7259977ea3ffa9c0da0447d61c7567d664df801fd8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.244"
