name = "Gemoded Ist Geil V2"
author = "Laputa Werkstatt"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2185a4e4e2a45f165d7c5484e72b00a3572d5b12cfdafab9aaa0ac94df1d06be"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.244"
