name = "Gemoded Ist Geil V2"
author = "Laputa Werkstatt"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "44645969ba42926391fe92680123e9f0233c70f77bfcdd663ebf42d2f16dda3e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.244"
